---
connections:
  type: "object"
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/connection"
  additionalProperties: false

connection:
  type: "object"
  properties:
    ipa_server:
      type: string
      description: "IP/Hostname of the FreeIPA server"
      required: true
    ipa_username:
      type: string
      description: "Username to login to the FreeIPA server"
      required: true
    ipa_password:
      type: string
      description: "Password to login to the FreeIPA server"
      required: true
      secret: true
    verify_ssl:
      type: boolean
      description: "Verify SSL certificates on the server"
      default: true
  additionalProperties: false
